config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


resources :users, only: [:show]

resources :employers, only: [:show, :new, :create] do
  resources :listings, only: [:new, :create] do
    resources :questions, only: [:new, :create, :show]
  end
end

resources :listings, only: [:index,:show] do
  resources :submissions, only: [:create]
end

resources :submissions, only: [:show, :destroy] do
  # resources :quizzes, only: [:show]
  resources :responses, only: [:index, :new, :create]
  resources :messages, only:[:index, :create]
end

post '/employers/:employer_id/listings/new', to: 'listings#create', as: :new_listing

get 'quizzes/:quiz_id/submissions/:id', to: 'quizzes#show', as: :take_quiz
patch 'submissions/:id/submit', to: 'submissions#submit', as: :submit
patch 'submissions/:id/confirm', to: 'submissions#confirm', as: :confirm
patch 'submissions/:id/reject', to: 'submissions#reject', as: :reject
mount ActionCable.server => "/cable"
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :employer
  belongs_to :quiz
  has_many :submissions, dependent: :destroy

  validates :description, presence: true
  validates :title, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :hours_per_week, presence: true
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    # if params[:query][:city] == ("" || nil)
    #   @listings = Listing.all
    # else
    #   @listings = Listing.joins(:employer).where(employers: {city: params[:query][:city].capitalize})
    # end
    @listings = Listing.all
    if params[:query]
      @city = params[:query][:city]
      @title = params[:query][:title]
    else
      params[:query] = {}
    end

    @listings = @listings.joins(:employer).where(employers: {city: @city.capitalize}) unless @city == "" || @city == nil
    @listings = @listings.where("title ILIKE ?", "%#{@title}%") unless @title == "" || @title == nil

    @all_listings = Listing.all
    session[:search] = params[:query]
    if current_user.nil?
    @submissions = []
    else
    @submissions = current_user.submissions
    end
  end

  def show
    if current_user.nil?
    @submissions = []
    else
    @submissions = current_user.submissions
    end
    @currentusersubmissionslistingids = []
    @submissions.each do |submission|
      @currentusersubmissionslistingids << submission.listing_id
    end
    @listing = Listing.find(params[:id])
    @markers = [{ lng: @listing.employer.longitude, lat: @listing.employer.latitude }]
  end

  def create
    @listing = Listing.new(listing_params)
    @quiz = Quiz.new
    @employer = Employer.find(params[:employer_id])
    @listing.update!(employer: @employer, quiz: @quiz)
    redirect_to new_employer_listing_question_path(@employer, @listing)
  end

  def new
    @listing = Listing.new
    @employer = Employer.find(params[:employer_id])
  end

  private

  def listing_params
    params.require(:listing).permit(:title, :description, :start_date, :end_date, :hours_per_week, :pay_per_hour)
  end
end

app/views/listings/index.html.erb
<div class="filter-wrapper">
<%= simple_form_for :query, :url => listings_path, method: "get" do |f| %>
  <div class="search-bar fixed">
    <div class="field">
      <%= f.input :city, as: :string, required: true, placeholder:'Location', label: false, input_html: {value: params[:query][:city], class: 'form-input field'} %>
    </div>
    <div class="field">
      <%= f.input :title, as: :string, required: true, placeholder:'Job Type', label: false, input_html: {value: params[:query][:title], class: 'form-input field'} %>
    </div>
    <div class="field final">
      <%= f.button :submit, "Filter", class: "btn btn-success socksup-secondary field" %>
    </div>
  </div>
  <% end %>
  <div class="listings-container">
    <% if @listings.count == 0 %>
    <!-- Displays a message if the search criteria is not met -->
    <p style="text-align: center; margin-top: 20px;"><strong>Oops, no job listings fit your search criteria!</strong> <br> Try something else ☺️</p>
    <% else %>
    <!-- Displays all the cards which match the search criteria -->
    <div class="row">
      <% @all_listings.each do |listing| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <%= link_to listing_path(listing) do %>
        <!-- The display none is added only to the listings which do not meet the search criteria  -->
        <div class="card box" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.4) 0%, rgba(0,36,61,0.4) 50%), url('<%= listing.photo %>'); <%= "display: none" unless @listings.include?(listing) %>" >
          <% @submissions.each do |submission| %>
          <% currentusersubmissionslistingid = submission.listing.id %>
          <% if listing.id == currentusersubmissionslistingid %>
              <div class="ribbon"><span>APPLIED</span></div>
          <% elsif listing.title == submission.listing.title %>
              <div class="ribbon-orange"><span>SUGGESTED</span></div>
          <% else %>
              <div></div>
          <% end %>
          <% end %>
          <div class="card-content">
            <div class="info">
              <h2 class="card-title"><%= listing.title %></h2>
              <h3 class="card-location"><%= listing.employer.city %></h3>
              <p class="card-description"><%= listing.employer.name %></p>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
    <% end %>
  </div>

</div>

app/views/listings/index.js.erb
function myFunction() {
  // Declare variables
  var input, filter, ul, li, a, i, txtValue;
  input = document.getElementById('city-search');
  filter = input.value.toUpperCase();
  ul = document.getElementById("resultsList");
  li = ul.getElementsByTagName('li');

  // Loop through all list items, and hide those who don't match the search query
  for (i = 0; i < li.length; i++) {
    cardLocation = li[i].querySelector("card-location")[0];
    txtValue = cardLocation.textContent || cardLocation.innerText;
    if (txtValue.toUpperCase().indexOf(filter) > -1) {
      li[i].style.display = "";
    } else {
      li[i].style.display = "none";
    }
  }
}

app/views/listings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
      <h1 id="h1-create-listing"></h1>
      <div>
        <div class="form-box">
          <p>Please enter the necessary information about your new job offer in the form below.</p>
          <div class="form-inputs">
            <%= simple_form_for @listing, url: employer_listings_path(@employer, @listing) do |f| %>
              <%= f.input :title, input_html: {class: "form-input"} %>
              <%= f.input :description, input_html: {class: "form-input"} %>
            <div class="form-input-dates">
              <%= f.input :start_date, as: :string, required: false, input_html: {class: "form-input datepicker"} %>
              <%= f.input :end_date, as: :string, required: false, input_html: {class: "form-input datepicker"} %>
            </div>
            <%= f.input :hours_per_week, input_html: {class: "form-input"} %>
            <%= f.input :pay_per_hour, input_html: {class: "form-input"} %>
            <%= f.button :submit, class: "btn-success socksup-primary small", id:"listing-enter" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/listings/show.html.erb
<!-- Banner picture  -->
<div class="banner-listing-show" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.4) 0%, rgba(0,36,61,0.4) 50%), url('<%= @listing.photo %>');">
  <%= link_to '<i class="fas fa-arrow-left"></i>'.html_safe, listings_path(:query =>{:city => session[:search]['city'], :title => session[:search]['title']}), class: "back-button-position" %>

  <div class="banner-content-listing-show">
    <h1><%= @listing.title %></h1>
    <h2><%= @listing.employer.name %></h2>
    <h3><i class="fas fa-map-marker-alt"></i><%= @listing.employer.city %></h3>
  </div>
</div>

<!-- Information displayed underneath banner picture -->
<div class="listing-show-job-info">
    <% if @currentusersubmissionslistingids.include?(@listing.id) %>
       <%= link_to 'View your Application', user_path(current_user), class: "btn btn-success socksup-primary btn-pin" %>
    <% elsif current_user && current_user.employer && (current_user.employer.id == @listing.employer.id)  %>
      <%= link_to 'View Applicants', user_path(current_user), class: "btn btn-success socksup-primary btn-pin" %>
    <% elsif current_user && current_user.employer && (current_user.employer.name != @listing.employer.name) %>
      <%= link_to 'View Company Profile', employer_path(@listing.employer), class: "btn btn-success socksup-primary btn-pin" %>
    <% elsif !user_signed_in? %>
      <%= link_to 'Take the quiz', new_user_session_path, class: "btn btn-success socksup-primary btn-pin" %>
    <% else %>
      <%= link_to 'Take the quiz', listing_submissions_path(@listing), method: :post, class: "btn btn-success socksup-primary btn-pin" %>
    <% end %>

  <!-- Links back to results page persisting the filters added before changing to show page -->

  <div class="listing-show-job-dates">
    <span style="float: left;" id="start_date"><p><i class="fas fa-walking"></i> Start Date<br> <%= @listing.start_date.strftime("%d/%m/%Y")  %></p></span>
     <span style="float: right;"id="end_date"><p>End Date <i class="fas fa-walking"></i><br> <%= @listing.end_date.strftime("%d/%m/%Y")  %></p></span>
  </div>
  <div class="listing-show-job-hours text-center">
    <p>Hours per week: <%= @listing.hours_per_week %> <i class="far fa-clock"></i></p>
    <p>Pay per hour: <%= "£#{@listing.pay_per_hour}" %> </i></p>

  </div>
    <hr id="job-info-hr">
  <div class="listing-show-job-description">
    <h4>About this job</h4>
    <p><%= @listing.description %></p>
  </div>
</div>

<!-- Displays a map with a marker on the location of the employer -->
<div class="horizontal">
    <div
    id="map"
    style="width: 75%;
    height: 400px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
    >
  </div>
  <div class="box-address-over-map">
    <p><strong>Address</strong></p>
    <p><%= @listing.employer.address %>, <%= @listing.employer.city %></p>
  </div>
</div>

<% content_for :meta_title, "#{@listing.title} job opportunity available on #{DEFAULT_META["SocksUp"]}" %>
<% content_for :meta_description, @listing.description %>
<% content_for :meta_image, @listing.photo %>