config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


resources :users, only: [:show]

resources :employers, only: [:show, :new, :create] do
  resources :listings, only: [:new, :create] do
    resources :questions, only: [:new, :create, :show]
  end
end

resources :listings, only: [:index,:show] do
  resources :submissions, only: [:create]
end

resources :submissions, only: [:show, :destroy] do
  # resources :quizzes, only: [:show]
  resources :responses, only: [:index, :new, :create]
  resources :messages, only:[:index, :create]
end

post '/employers/:employer_id/listings/new', to: 'listings#create', as: :new_listing

get 'quizzes/:quiz_id/submissions/:id', to: 'quizzes#show', as: :take_quiz
patch 'submissions/:id/submit', to: 'submissions#submit', as: :submit
patch 'submissions/:id/confirm', to: 'submissions#confirm', as: :confirm
patch 'submissions/:id/reject', to: 'submissions#reject', as: :reject
mount ActionCable.server => "/cable"
end

app/models/user.rb
class User < ApplicationRecord
   mount_uploader :photo, PhotoUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :submissions,  dependent: :destroy
  belongs_to :employer, optional: true

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true
  # validates :date_of_birth, presence: true
  # validates :photo, presence: true
  # validates_presence_of   :photo
  # validates_integrity_of  :photo
  # validates_processing_of :photo

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    if @user.employer_id
      @inbound_submissions = []
      @user.employer.listings.each do |l|
        l.submissions.each do |s|
          @inbound_submissions.push(s)
        end
      end
      @inbound_submissions = @inbound_submissions.sort_by{|x| x.created_at}.reverse
    end
  end


end

app/views/users/show.html.erb
<!-- Background picture with profiule picture on top -->
<div class="banner-profile" style="background-image: url('https://d2v9y0dukr6mq2.cloudfront.net/video/thumbnail/4RUieTItxik2c5fvx/simple-animated-geometric-background-with-squares-4k-ultra-high-definition-video-loop_hzhlwak8x_thumbnail-full01.png')">
   <div class="invisible-button-refresh">
    <%= link_to "", user_path(current_user), class: "invisible-button-refresh"%>
  </div>
  <div class="banner-content-profile">
    <% if current_user.employer %>
    <div class="new-listing-button"> <%= link_to "Add New Job Listing",  new_employer_listing_path(current_user.employer), class: "btn btn-success socksup-primary small response-button" %></div>
    <h3><%= current_user.employer.name %></h3>
    <% else %>
    <h3><%= current_user.first_name%> <%= current_user.last_name%></h3>
    <% end %>

    <% if current_user.employer %>
    <%= cl_image_tag current_user.employer.photo, class: "profile-picture", width: 70, height: 70 %>
    <%= cl_image_tag current_user.photo, class: "profile-picture-tiny", width: 70, height: 70 %>
    <% else %>
    <%= cl_image_tag current_user.photo, class: "profile-picture", width: 70, height: 70 %>
    <% end %>
  </div>
</div>

<!-- If a user is an applicant it will show the jobs they user has applied for, if it is an employer it will show applicants -->
<div class="inbox-container">
  <% if  @user.employer %>
  <%= render 'shared/employer-listings-inbox' %>
  <% else %>
  <%= render 'shared/user-submissions-inbox' %>
  <% end %>
</div>