config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


resources :users, only: [:show]

resources :employers, only: [:show, :new, :create] do
  resources :listings, only: [:new, :create] do
    resources :questions, only: [:new, :create, :show]
  end
end

resources :listings, only: [:index,:show] do
  resources :submissions, only: [:create]
end

resources :submissions, only: [:show, :destroy] do
  # resources :quizzes, only: [:show]
  resources :responses, only: [:index, :new, :create]
  resources :messages, only:[:index, :create]
end

post '/employers/:employer_id/listings/new', to: 'listings#create', as: :new_listing

get 'quizzes/:quiz_id/submissions/:id', to: 'quizzes#show', as: :take_quiz
patch 'submissions/:id/submit', to: 'submissions#submit', as: :submit
patch 'submissions/:id/confirm', to: 'submissions#confirm', as: :confirm
patch 'submissions/:id/reject', to: 'submissions#reject', as: :reject
mount ActionCable.server => "/cable"
end

app/views/shared/_card.html.erb
<!-- <div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1511421616335-5a9846f1afcb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2689&q=80');">
        <div class="card-content">
          <div class="info">
            <h2 class="card-title">Job Position</h2>
            <h3 class="card-location">City</h3>
            <p class="card-description">The company name</p>
            <a class="card-link" href="#"></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


 -->

app/views/shared/_employer-listings-inbox.html.erb
<div class="inbox-container"></div>
  <div class="inbox">
    <h4>Applicants</h4>
    <p><%@inbound_submissions.each do |s|%></p>
    <div class="inbox-card">
      <div class="inbox-info inbox-info-left">
        <%= cl_image_tag s.user.photo, class: "profile-picture-inbox" %>
          <p class="applicant-name"><%= "#{s.user.first_name}" " #{s.user.last_name}"%></p>
        <div class="small listing-title-position">
          <strong><%= "#{s.listing.title}" %></strong>
        </div>
      </div>
      <div class="inbox-info">
        <% if s.confirmed.nil?%>
           <i class="far fa-clock"></i>
           <p class="awaiting-response">Awaiting <br> Response</p>
           <%= link_to "View Application",submission_path(s), class: "btn btn-success socksup-primary small response-button" %>
        <% elsif s.confirmed == true%>
          <i class="fas fa-check"></i>
          <p id="accepted"> <strong>Accepted!</strong></p>
          <%= link_to "Messages", submission_messages_path(s), class: "btn btn-success socksup-primary small response-button" %>
        <% else s.confirmed == false%>
          <p style="color: red;">Rejected</p>
        <% end %>
      </div>
    </div>
        <hr width="50%">
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert" id="flash">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert" id="flash">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer <% if @footer_position_relative %>footer-position-relative <% end %> fixed-bottom">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-socksup navbar-static-top">
  <!-- Logo -->
  <% if params[:controller] == "messages" && params[:action] == "index"  %>
    <%= link_to '<i class="fas fa-arrow-left"></i>'.html_safe, url_for(:back), class: 'chat-back-button' %>



      <% if current_user.employer %>
       <div class="contact-information">
        <h4>
          <%= link_to "#{@submission.user.first_name} #{@submission.user.last_name}", user_path(@submission.user), :class => "brand-link" %>
        </h4>
       </div>
       <% else %>
       <div class="contact-information">
       <h4><%= link_to "#{@submission.listing.employer.name}", employer_path(@submission.listing.employer) , :class => "brand-link" %></h4`>
       </div>
       <% end %>


  <% else %>
    <%= link_to root_path, class: "navbar-socksup-brand" do %>
      <%= image_tag "socks.png", height: 50 %>
    <% end %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-socksup-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
    <!-- Links when logged in -->
    <%= link_to "Profile", user_path(current_user), class: "navbar-socksup-item navbar-socksup-link" %>
    <!-- Avatar with dropdown menu -->
    <div class="navbar-socksup-item">
      <div class="dropdown">
        <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-socksup-menu", "data-toggle" => "dropdown"  %>
        <ul class="dropdown-menu dropdown-menu-right navbar-socksup-dropdown-menu">
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <% else %>
    <!-- Login link (when logged out) -->
    <%= link_to t(".sign_in", default: "Log in"), new_user_session_path, class: "navbar-socksup-item navbar-socksup-link" %>
    <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "navbar-socksup-item navbar-socksup-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-socksup-item hidden-md hidden-lg">
    <% if user_signed_in? %>
    <!-- Links when logged in -->
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-socksup-dropdown-menu">
        <li><%= link_to "Profile", user_path(current_user), class: "navbar-socksup-item navbar-socksup-link" %></li>
        <li><%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %></li>
        </ul>
        <% end %>
      </div>

      <% else %>

      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-socksup-dropdown-menu">
          <li><%= link_to t(".sign_in", default: "Log in"), new_user_session_path, class: "navbar-socksup-item navbar-socksup-link" %>
          </li>
          <li><%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "navbar-socksup-item navbar-socksup-link" %></li>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_user-submissions-inbox.html.erb
<div class="inbox">
  <br>
  <h4>Applications</h4>
  <% if @user.submissions.count == 0 %>
  <!-- Display message if the user has not yet applied for any jobs -->
  <div class="inbox-card">
    <p><strong>You haven't applied for any jobs yet</strong></p>
    <%= link_to "Search a job now", listings_path, class: "btn btn-success socksup-primary no-apply"%>
  </div>
  <% else %>
  <!-- Display all jobs which the user has applied for showing newest first -->
  <% @user.submissions.reverse.each do |s| %>
  <div class="inbox-card">
    <div class="inbox-info inbox-info-left">
      <div class="big">
        <%= "#{s.listing.title}"%>
      </div>
      <div class="small">
        <%= "#{s.listing.start_date.strftime("%d %b %y")} - #{s.listing.end_date.strftime("%d %b %y")}" %>
      </div>
      <div class="small">
        <strong><%= "#{s.listing.employer.name}"%></strong>
      </div>
    </div>
    <div class="inbox-info">
      <% if s.confirmed.nil?%>
      <i class="far fa-clock"></i>
      <p class="awaiting-response">Awaiting Response</p>

        <%= button_to "Cancel", user_path(current_user), method: :patch, id: "cancel", remote: :true, "data-toggle" => "modal", "data-target" => "#confirmCancel", "data-backdrop"=> "static", "data-keyboard" => "false"%>


<!-- MODAL -->

<div class="modal fade" id="confirmCancel" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header text-center green-top">
        <h3  id="modalCenterTitle">Dont give up!</h3>
      </div>
      <div class="modal-body green-body">
        <%= "Are you sure you want to cancel your application to be a #{s.listing.title.downcase} at #{s.listing.employer.name}? \n It's not too late! They haven't rejected you!" %>
      </div>
      <div>
        <div class="modal-footer modal-center-text">
          <div class="modal-button">
            <%= link_to 'Nevermind', user_path(current_user), class: "btn btn-success socksup-primary" %>
          </div>
          <div class="modal-button">
            <%= link_to 'Cancel Application', submission_path(s), method: :delete, class: "btn btn-success socksup-secondary" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- END MODAL -->




      <% elsif s.confirmed == true%>
      <i class="fas fa-check"></i>
      <p id="accepted"> <strong>Accepted!</strong></p>
      <%= link_to "Messages", submission_messages_path(s), class: "btn btn-success socksup-primary no-apply small" %>
      <% else s.confirmed == false%>
      <p style="color: red; font-weight: bold;">Rejected</p>
      <% end %>
    </div>
  </div>
  <hr width="50%">
  <% end %>
  <% end %>
</div>