config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


resources :users, only: [:show]

resources :employers, only: [:show, :new, :create] do
  resources :listings, only: [:new, :create] do
    resources :questions, only: [:new, :create, :show]
  end
end

resources :listings, only: [:index,:show] do
  resources :submissions, only: [:create]
end

resources :submissions, only: [:show, :destroy] do
  # resources :quizzes, only: [:show]
  resources :responses, only: [:index, :new, :create]
  resources :messages, only:[:index, :create]
end

post '/employers/:employer_id/listings/new', to: 'listings#create', as: :new_listing

get 'quizzes/:quiz_id/submissions/:id', to: 'quizzes#show', as: :take_quiz
patch 'submissions/:id/submit', to: 'submissions#submit', as: :submit
patch 'submissions/:id/confirm', to: 'submissions#confirm', as: :confirm
patch 'submissions/:id/reject', to: 'submissions#reject', as: :reject
mount ActionCable.server => "/cable"
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :user
  belongs_to :listing
  has_many :responses, dependent: :destroy
  has_many :messages
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  def create
    @submission = Submission.new
    @submission.user = current_user
    @submission.listing = Listing.find(params[:listing_id])
    @submission.save
    redirect_to take_quiz_path(Listing.find(params[:listing_id]).quiz, @submission)
  end

  def show
    @submission = Submission.find(params[:id])
  end

  def submit
    @submission = Submission.find(params[:id])
    @submission.submitted = true
    @submission.save
  end

  def confirm
    @submission = Submission.find(params[:id])
    @submission.confirmed = true
    @submission.save
    redirect_to user_path(current_user)
  end

  def reject
    @submission = Submission.find(params[:id])
    @submission.confirmed = false
    @submission.save
    redirect_to user_path(current_user)
  end

  def destroy
    @submission = Submission.find(params[:id])
    @submission.destroy
    redirect_to user_path(current_user)
  end

end

app/views/submissions/show.html.erb
<div class="container" id="response-page">
  <!-- Heading is different depending on who is viewing the page. If employer, applicants name will display, if user, your responses will display -->
  <% if current_user.employer %>
  <%= link_to '<i class="fas fa-arrow-left"></i>'.html_safe, url_for(:back), class: 'response-back-button' %>
  <h3 class="main-heading text-center heading-margin"><%= @submission.user.first_name %>'s  responses!</h3>

  <% else %>
  <h3 class="main-heading text-center">Here are your responses!</h3>
  <% end %>
  <!-- Shows a summary of the questions and the responses given by the applicant -->
  <div class="responses">
      <% @submission.responses.each do |r| %>
    <div class="response">
      <h4><%= r.question.question %></h4>
      <p><%= r.content %></p>
      <hr>
    </div>
    <% end %>
  </div>

<!-- If it is an employer viewing the page they will see the accpet or reject buttons -->
  <% if current_user.employer == @submission.listing.employer %>
  <div class="accept-reject-buttons">
    <%= button_to "Accept", confirm_path(@submission), method: :patch, class: "btn btn-success socksup-primary response-button", id: "submit-button" %>
    <%= button_to "Reject", reject_path(@submission), method: :patch, class: "btn btn-success socksup-primary response-button", id: "submit-button" %>
  </div>

<!-- If it is a user viewing they will have the option to. submit their application -->
  <% elsif @submission.user == current_user%>
  <%= button_to "Submit application", submit_path(@submission), method: :patch, class: "btn btn-success socksup-primary response-button", id: "submit-button", remote: :true, "data-toggle" => "modal", "data-target" => "#confirmSubmission", "data-backdrop"=> "static", "data-keyboard" => "false"%>
  <% end %>
</div>

<!-- A modal which will appear once the user has pressed the submit button above -->
<div class="modal fade" id="confirmSubmission" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header text-center green-top">
        <h3  id="modalCenterTitle">Congratulations!</h3>
      </div>
      <div class="modal-body green-body">
        <%= "You've successfully submitted your quiz to be a #{@submission.listing.title.downcase}. #{@submission.listing.employer.name} will review your application and their contact details will be available to you if your application is approved." %>
      </div>
      <div>
        <div class="modal-footer modal-center-text">
          <div class="modal-button">
            <%= link_to 'Look for More Jobs', listings_path, class: "btn btn-success socksup-primary" %>
          </div>
          <div class="modal-button">
            <%= link_to 'See My Applications', user_path(@submission.user), class: "btn btn-success socksup-secondary" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/submissions/submit.js.erb
const box = document.getElementById('submit-button');
box.insertAdjacentHTML('afterend', '<div>Submitted</div>');
box.remove();